version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
      - app_data:/app/data
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

volumes:
  app_data: 